Repository adansons/base, pull requests merged in 2022-04, with the labels that each got.

#2 bug fix
  README.md
Labels: documentation

#7 fixed to use GITHUB_TOKEN
  .github/workflows/ci.yml
Labels: Automate, bug

#3 change the error message displyed when an incorrect api-key is entered
  base/config.py
Labels: Improvement

#1 Update README.md
  README.md
Labels: documentation

#4 Update README.md
  README.md
Labels: documentation

#10 fixed README
  README.md
Labels: documentation

#12 fixed python reference link
  README.md
Labels: documentation

#13 add CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation

#15 Update README.md
  README.md
Labels: documentation

#18 update README
  README.md
Labels: documentation

#21 fixed link for SDK docs
  README.md
Labels: bug, documentation
