Repository adansons/base, pull requests merged in 2022-05, with the labels that each got.

#23 add link to medium
  README.md
Labels: documentation

#26 Update filename in tutorial notebook
  example/01_mnist_tutorial.ipynb
Labels: Improvement

#30 Support Japanese
  .github/workflows/ci.yml
  .gitignore
  base/project.py
  tests/data/sample.xlsx
Labels: bug

#41 Supported `+` and `|` operators for `Files`
  base/dataset.py
  base/files.py
  docs/SDK.md
Labels: enhancement

#43 Feature/#28
  README.md
  docs/CLI.md
  example/01_mnist_tutorial.ipynb
Labels: documentation

#49 added description for `Files` and `Dataset`
  docs/SDK.md
Labels: documentation

#50 update `base show` output to know keys on metadata DB easily
  base/cli.py
  base/project.py
  docs/CLI.md
  docs/SDK.md
  tests/test_cli.py
  tests/test_project.py
Labels: enhancement

#53 increment version 0.1.0 -> 0.1.1
  base/__init__.py
  base/cli.py
  pyproject.toml
Labels: documentation

#54 v0.1.1
  base/__init__.py
  base/cli.py
  pyproject.toml
Labels: documentation

#56 Update jupyternotebook :Consistent with README.md
  README.md
  example/01_mnist_tutorial.ipynb
Labels: Improvement
